import type { NextPage } from 'next';
import Head from 'next/head';
import { App } from '../components';
import { GetStaticProps } from 'next';
import axios from 'axios';

const Home: NextPage = ({ data }: any) => {
	return (
		<div>
			<Head>
				<title>Edvora App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='container mx-auto h-screen w-screen bg-background'>
				<App data={data} />
			</div>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async () => {
	const res: any = await axios.get('https://assessment.api.vweb.app/rides');

	return {
		props: {
			data: res.data,
		},
	};
};

export default Home;
